title: Daniel
description: Operations Research
logo: images/meme.jpeg
show_downloads: no

theme: jekyll-theme-minimal

markdown: kramdown
highlighter: rouge

exclude:
  - README.md
  - node_modules
  - vendor
